### ISSUE TITLE
Opensource

### ISSUE THREAD

**Issue by rtrevorclark** [google/prudaq#27]
Why was closed source software used to make the open source hardware. i.e. why not use KiCad instead of eagle?

**Comment by credentiality** [comment]
I did try.  For a project a few years back I used geda/gschem.  This time I tried 3 or 4 of the more popular Free solutions, and couldn't make them work in a reasonable time frame, so I fell back to Eagle.

**Comment by rtrevorclark** [comment]
Hey I'm glad to hear you tried. Keep up the good work!
